name: neuraloperator
channels:
  - pyrocko
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python & Machine Learning
  - python=3.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pytorch-cuda=12.1
  - deepxde=1.9.3
  - jax=0.4.13
  
  # Data Science & Math
  - numpy=1.24.4
  - scipy=1.10.1
  - pandas=2.0.3
  - scikit-learn=1.3.2
  - scikit-optimize=0.9.0
  - sympy=1.12
  - networkx=3.1
  - h5py=3.10.0
  
  # Visualization & Logging
  - matplotlib=3.7.3
  - wandb=0.15.12
  - tqdm=4.66.1
  - ipykernel=6.26.0
  
  # Physics, Rendering & Specialized Tools
  - pyrocko=2024.01.10
  - pybullet=3.25
  - urdfpy=0.0.22
  - pyrender=0.1.45
  - beautifulsoup4=4.12.3
  
  # Pip specific dependencies
  - pip
  - pip:
      - cython==3.0.10
      - gridijkstra==0.1
      - imageio==2.35.1
      - jaxlib==0.4.13
      - mesh-to-sdf==0.0.15
      - pqdict==1.4.0
      - pyglet==2.0.17
      - pykonal==0.4.1
      - pyopengl==3.1.0
      - pywavelets==1.4.1
      - scikit-fmm==2024.5.29
      - scikit-image==0.21.0
      - tifffile==2023.7.10
      - torch-summary==1.4.5
      - trimesh==4.4.9
